### Understanding Vector spaces

In [1]:
img1 = "/Users/karthickdurai/Downloads/botox_dataset/after/0.png"
img2 = "/Users/karthickdurai/Downloads/botox_dataset/after/1.png"

In [2]:
from PIL import Image

In [12]:
try:
    # Open the image
    # img = Image.open(img1)

    # Display the image
    print(img.size)
    cropped_img = img.crop((45, 20, 200, 200))
    print(Image.open(img2).size)
    # cropped_img.show()
    # img.show()

except FileNotFoundError:
    print(f"Error: Image file not found at {image_path}")
except Exception as e:
    print(f"An error occurred: {e}")

(382, 533)
(396, 378)


##### Let's try resizing the image

In [20]:
try:
    img = Image.open(img1)
    resized_img = img.resize((28, 28))
    img_ = Image.open(img2)
    res_img2 = img_.resize((28, 28))
    print(type(res_img2))
    # res_img2.show()
    # resized_img.show()


except Exception as e:
    print(e)

<class 'PIL.Image.Image'>


In [32]:
try:
    import numpy as np
    arr1 = np.asarray(resized_img, dtype=np.uint16)
    arr2 = np.asarray(res_img2, dtype=np.uint16)
    sum_arr = arr1 + arr2
    sum_clipped = np.clip(sum_arr, 0, 255).astype(np.uint8)
    sum_div = (sum_arr // 2).astype(np.uint8)
    print(sum_div)
    result = Image.fromarray(sum_div)
    result.show()
except Exception as e:
    print(e)

[[[ 81 115 140 255]
  [ 83 117 142 255]
  [ 84 118 144 255]
  ...
  [104 135 162 255]
  [103 135 161 255]
  [103 134 159 255]]

 [[ 78 112 138 255]
  [ 79 114 140 255]
  [ 80 115 141 255]
  ...
  [101 133 160 255]
  [102 134 160 255]
  [101 132 159 255]]

 [[ 78 112 138 255]
  [ 80 114 140 255]
  [ 81 115 142 255]
  ...
  [102 133 158 255]
  [103 134 161 255]
  [102 134 160 255]]

 ...

 [[ 77  67  48 255]
  [ 77  66  47 255]
  [120  96  69 255]
  ...
  [116  83  50 255]
  [125  92  62 255]
  [139 108  74 255]]

 [[ 56  49  40 255]
  [ 70  61  45 255]
  [115  89  61 255]
  ...
  [112  86  58 255]
  [112  86  61 255]
  [130 102  68 255]]

 [[ 61  57  46 255]
  [ 70  59  43 255]
  [108  87  61 255]
  ...
  [132 106  75 255]
  [143 120  88 255]
  [145 120  85 255]]]


#### Let's prove the 10 axioms of vector spaces over this image dataset

There are mainly 2 axioms, when it comes to vector space proving:

1. addition over vectors
2. scalar multiplication over vectors